name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      test:
        description: publish to test pypi
        required: false
        default: false
        type: boolean

  # Change to this once workflow has been tested
  # on:
    # release:
    #   types: [released]

jobs:

  build_artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.11'

    - name: Install build tools
      shell: 'bash'
      run: python -m pip install build

    - name: Build sdist
      shell: 'bash'
      run: python -m build --sdist --wheel .

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*

  publish_testpypi:
    needs: [ build_artifacts ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: ${{ inputs.test }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      
      - name: Publish package distributions to TEST PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          name: testpypi
          user: ${{ secrets.PYPI_USERNAME_SPACEKIT_MAINTAINER }}
          password: ${{ secrets.PYPI_PASSWORD_SPACEKIT_MAINTAINER_TEST }}
          repository-url: https://test.pypi.org/legacy/
          verify-metadata: true
          skip-existing: false
          verbose: true

  publish_pypi:
    needs: [ build_artifacts ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    if: ${{ inputs.test == 'false' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          name: pypi
          user: ${{ secrets.PYPI_USERNAME_SPACEKIT_MAINTAINER }}
          password: ${{ secrets.PYPI_PASSWORD_SPACEKIT_MAINTAINER }}
          repository-url: https://pypi.org/p/spacekit
          verify-metadata: true
          skip-existing: false
          verbose: false
